stages:
  preprocess:
    cmd: python src/data_processing.py
    deps:
      - src/data_processing.py
      - data/raw/kidney.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
      - models/random_forest_model.pkl